spring.application.name=felana-backend

# Profil actif par défaut
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.servlet.context-path=/api

#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuration de secours pour Render si le profil sous-jacent est lent à charger
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# Forcer Hibernate à utiliser PostgreSQL quoi qu'il arrive
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Valeurs par défaut du magasin
app.magasin.nom=Felana Friperie & Artisanat
app.magasin.adresse=Toamasina
app.magasin.telephone=+261 34 00 000 00
app.magasin.taux-taxe=0.0