# Base de données distante ( Supabase)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# En Prod, on ne laisse pas Hibernate modifier la base automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Clé secrète JWT issue des variables d'environnement de Render
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
jwt.client-token-expiration=86400000

# Spring Mail Configuration (Production)
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.otp.expiration-minutes=10

app.magasin.nom=Felana Friperie & Artisanat
app.magasin.adresse=Toamasina, Madagascar
app.magasin.telephone=+261 34 00 000 00
app.magasin.taux-taxe=0.0

app.bootstrap.gerant.name=${APP_BOOTSTRAP_GERANT_NAME}
app.bootstrap.gerant.email=${APP_BOOTSTRAP_GERANT_EMAIL}
app.bootstrap.gerant.password=${APP_BOOTSTRAP_GERANT_PASSWORD}