# Base de données PostgreSQL locale
spring.datasource.url=jdbc:postgresql://localhost:5432/friperie_db
spring.datasource.username=postgres
spring.datasource.password=scrTmg123 Diolin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration JWT
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckpXVFNpZ25pbmdDaGFuZ2VJdEluUHJvZA==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
jwt.client-token-expiration=86400000

# Configurations du Gérant au démarrage
app.bootstrap.gerant.name=Gérant Principal
app.bootstrap.gerant.email=gerant@admin.com
app.bootstrap.gerant.password=MonSuperMotDePasse123!

# Configuration du serveur de messagerie pour l'envoi d'e-mails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=razafimahatratradiolin@gmail.com
spring.mail.password=jqip rtsv olrh afvb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.otp.expiration-minutes=10

spring.security.debug=true

# Informations boutique (environnement local/dev)
app.magasin.nom=Felana Friperie & Artisanat
app.magasin.adresse=Antananarivo, Madagascar
app.magasin.telephone=+261 XX XX XXX XX
app.magasin.taux-taxe=0.0