# Base de données PostgreSQL locale
spring.datasource.url=jdbc:postgresql://localhost:5432/friperie_db
spring.datasource.username=postgres
spring.datasource.password=scrTmg123 Diolin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration JWT
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckpXVFNpZ25pbmdDaGFuZ2VJdEluUHJvZA==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
jwt.client-token-expiration=86400000

# Configurations du Gérant au démarrage
app.bootstrap.gerant.name=G\u00e9rant Principal
app.bootstrap.gerant.email=gerant@admin.com
app.bootstrap.gerant.password=MonSuperMotDePasse123!

# Configuration du serveur de messagerie pour l'envoi d'e-mails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=razafimahatratradiolin@gmail.com
spring.mail.password=jqip rtsv olrh afvb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.otp.expiration-minutes=10

spring.security.debug=true

# Informations boutique (environnement local/dev)
app.magasin.nom=Hiba cr\u00e9ation Toamasina
app.magasin.adresse=Toamasina, Madagascar
app.magasin.telephone=+261 34 00 000 00
app.magasin.taux-taxe=0.0
app.magasin.mvola-numero=038 17 656 56
app.magasin.airtel-money-numero=033 67 658 01
app.magasin.orange-money-numero=032 98 114 55
app.magasin.email=hiba.fefe@gmail.com
app.magasin.whatsapp=033 67 658 01
app.magasin.nif-stat=4008473343 / 47190 31 2018 0 01186
